function pool: missing includes
Fix missing includes and compile errors of the form:
```
rocFFT/library/src/device/generator/../../include/function_pool.h:143:31: error: no member named 'max_element' in namespace 'std'
        auto itr       = std::max_element(supported.cbegin(), supported.cend());
                         ~~~~~^
```